PROMPT="[%F{white}%n%f@%F{white}%m%f(${ret_status}) %F{white}%T%f %l]
<%/>
%F{red}[%h]%f %{$reset_color%}"

compdef '_files -W /root/HOL7712-Solaris-Puppet/manifests -F site-copy.pp' lab_copy
lab_copy () {
# This is getting towards magic and inscrutable meta programming
FACTER_tag=$1 puppet apply /root/HOL7712-Solaris-Puppet/site-copy.pp --tags $1
}

# build and install lab module
lab_build () {
	( cd /root/*-lab
	puppet module build
	puppet module install --force ./pkg/*-lab-0.1.0.tar.gz
	)
}
