PROMPT="[%F{white}%n%f@%F{white}%m%f(${ret_status}) %F{white}%T%f %l]
<%/>
%F{red}[%h]%f %{$reset_color%}"

compdef '_files -W /root/HOL7712-Solaris-Puppet/manifests -F site-copy.pp' lab_copy
lab_copy () {
  puppet apply -t /root/HOL7712-Solaris-Puppet/site-copy.pp --tags $1
}
